included:
  - Sources
  - Tests
disabled_rules:
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - nesting
  - trailing_comma
  - statement_position
  - large_tuple
  - type_name
  - unneeded_synthesized_initializer
opt_in_rules:
  - empty_count
  - closure_spacing
